require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable

Rails/Output:
  Exclude:
    - db/**/*

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  # Default is 5
  Max: 10
